name: Release Chart

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - name: Add dependency repos
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm dependency update charts/k8s-grafana-stack

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package chart
        run: helm package charts/k8s-grafana-stack

      - name: Push chart
        run: helm push k8s-grafana-stack-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
